### ISSUE TITLE
What about the rest of the content?

### ISSUE THREAD

**Issue by mamoo** [Hack-Your-Future-Group-A-Dream-Team/iSchool#14]
- [x] Think about a strategy on content production
- [x] Make a list of content that has to be produced soon

**Comment by razvanbrb** [comment]
Hey @fmkarakus , @IrynaSpyrydonova  can you check the document about content. Let me know what you think and if I have to change something. Thanks
[iSchool-Content.docx](https://github.com/Hack-Your-Future-Group-A-Dream-Team/iSchool/files/5759104/iSchool-Content.docx)

**Comment by fmkarakus** [comment]
Hey @razvanbrb  and @julia-sod , here is my summary about info page.

[info page summary.docx](https://github.com/Hack-Your-Future-Group-A-Dream-Team/iSchool/files/5761601/info.page.summary.docx)

**Comment by razvanbrb** [comment]
Hey @fmkarakus  in my opinion is not much but if you think is enough then is ok. And if you add the link of the source then the user can be directed there and he can read more about it.

**Comment by razvanbrb** [comment]
![zoom](https://user-images.githubusercontent.com/22944865/103485981-ba700b80-4dfa-11eb-8140-eef33be69b8c.PNG)
