### ISSUE TITLE
Landing Page: Register on site

### ISSUE THREAD

**Issue by fmkarakus** [Hack-Your-Future-Group-A-Dream-Team/iSchool#18]
As a parent I want to be able to register on the site so that I can use additional properties of the website

Acceptance Criteria
• A user gets a registration form after clicking the “register” button.
• A user cannot submit a form without completing all the mandatory fields.
• Information from the form is stored in the registrations database.

Dependency: Registration form

**Comment by razvanbrb** [comment]
Hey @fmkarakus  What do you mean register on the site? Is not the same as Sign Up?

**Comment by fmkarakus** [comment]
Hey @razvanbrb , indeed, it is same as sign up.

**Comment by razvanbrb** [comment]
Ok thanks  @fmkarakus   then I think this one is not need it since Ira is busy with Sign in Sign up if I am not wrong?

**Comment by razvanbrb** [comment]
Relate #35
