### ISSUE TITLE
Landing Page: Sign in

### ISSUE THREAD

**Issue by fmkarakus** [Hack-Your-Future-Group-A-Dream-Team/iSchool#19]
As a parent I want to be able to sign in so that I can use additional properties of the website like accessing the favorite schools, commenting, adding stars to desired schools

Acceptance Criteria
• In order to sign in a user can enter username and password in dedicated fields and press sign in button
• A user can get predefined hint question in order to remember the password

Dependency: User information should be already stored in registrations database

**Comment by razvanbrb** [comment]
Relate #35
