### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by razvanbrb** [Hack-Your-Future-Group-A-Dream-Team/iSchool#2]

**Comment by razvanbrb** [comment]
HEy Team. I have take the advice from Maurizio to check the other similiar website.
 I have check the site that Iryna showed us niche.com where you can search a school. 
 I have seen that if you click Sing up or Sign in an pop will appear , not a  hole new page. So I think we don't need also  new pages for Sing in and Sing up. 
 
Let me know what do you think? 


![Log in](https://user-images.githubusercontent.com/22944865/102976590-15078e80-4502-11eb-8256-4b0833e027ab.PNG)
![sing up](https://user-images.githubusercontent.com/22944865/102976616-1f298d00-4502-11eb-92c9-69a364770ecd.PNG)

**Comment by razvanbrb** [comment]
Hey Guys I have created Mind Mapping with Flow Map and invited you also.  @fmkarakus  Did you had time to change the Wireframe from info page and search page?

**Comment by julia-sod** [comment]
Hi, Razvan! I think it's a good idea to make sign in and sign up as pop up pages. I guess they should be made in wireframe anyway though.

**Comment by razvanbrb** [comment]
The link to the wireframes : https://docs.google.com/presentation/d/1Nf3GKmADXxrkGapRWJsb_zLqE1m5kPEVwz4W7--3rtc/edit#slide=id.ga9643aaaaf_0_105
