### ISSUE TITLE
User Account Page: status of interaction with a particular school

### ISSUE THREAD

**Issue by IrynaSpyrydonova** [Hack-Your-Future-Group-A-Dream-Team/iSchool#24]
#### As a parent I want be able to see the status of my interaction with a particular school
	
_Acceptance Criteria_

Within each item of his list user can see dropdown list with the following  statuses:
   - researching
   - scheduled tour
   - started applications
   - applied
   - accepted

**Comment by razvanbrb** [comment]
Don't have to do this one.
