### ISSUE TITLE
User Account Page: manipulate data from the list of favourite/saved schools

### ISSUE THREAD

**Issue by IrynaSpyrydonova** [Hack-Your-Future-Group-A-Dream-Team/iSchool#25]
#### As a parent I want to be able to check all  details of each school from my list or delete it.
	
_Acceptance Criteria_

- Within each item of his list user can checked details of the school 
- Within each item of his list user can delete school from his list

_Dependency_:

 All information about the schools should be already saved in database

**Comment by razvanbrb** [comment]
Done.
