### ISSUE TITLE
User Account Page: compare schools from a user list

### ISSUE THREAD

**Issue by IrynaSpyrydonova** [Hack-Your-Future-Group-A-Dream-Team/iSchool#26]
#### As a parent I want to be able to compare schools, that I have been saved
	
_Acceptance Criteria_

- User can choose which schools he would like to compare and click the button, after what he will get the window/ page, with all details of selected schools.

_Dependency_:

 All information about the schools should be already saved in database

**Comment by razvanbrb** [comment]
Not a must. It would be nice if we have time.
