### ISSUE TITLE
Check statistics

### ISSUE THREAD

**Issue by okozmovskaya** [Hack-Your-Future-Group-A-Dream-Team/iSchool#29]
As a school-manager (SM) I want to be able to check statistics views of my school to understand the school’s popular

Acceptance criteria:

a SM gets a chart or table with number of visits of my school for particular period after click on “”show-number-of-visits” button.
information about quantity of clicks on particular school logs and saves in “number visit school” database.
Dependency: JavaScript library for data visualisation (for example, chart.js)

**Comment by razvanbrb** [comment]
Not  a must.

**Comment by razvanbrb** [comment]
Bye bye
