### ISSUE TITLE
Add new school 

### ISSUE THREAD

**Issue by okozmovskaya** [Hack-Your-Future-Group-A-Dream-Team/iSchool#32]
As a SM I want to be able to add my school in the site, it makes my school more popular

Acceptance criteria:

a SM gets a registration form after clicking the “add-my-school” button in SM-account.
a SM cannot submit a form without completing all the mandatory fields.
information from the form is stored in the schools database
after confirmation the managing school add to school-manager account
link this SM with particular school inside database
Dependency: Registration form

**Comment by razvanbrb** [comment]
Duplicate issue #53
