### ISSUE TITLE
user-stories idea

### ISSUE THREAD

**Issue by Feruzteame** [Hack-Your-Future-Group-A-Dream-Team/iSchool#8]
# Landing Page
### Read site information
- As a site visitor I need to know how the site works and what kind of information can I get so that it helps me to avoid confusion

**Acceptance Criteria**
- It should be clear

### Sign in
- As a site visitor, I need to sign in on the site then I can save my favorites a school,  get new information and ask a question

**Acceptance Criteria**
- A site visitor should fill the form include password
- Get registered confirmation

# Search School

### Apply search filters
- As a site user, I need to search for a school by giving criteria

**Acceptance Criteria**
- User should fill the form to get what he/she wants

### Submit query
- As a user, I want to see the resulting directly then I can choose what I prefer

**Acceptance Criteria**
- User should click the submit button to see the result

### Save my favorites schools
- As a site visitor I need to save the schools and I can find easily another time

**Acceptance Criteria**
- To save favorites schools the user should be signed in to the site

### View school detail
- As a user, I need to know the school detail so that it helps me to decide the right school
- As a school manager, I need to add needed information to the school profile so parents can have easy information access

**Acceptance Criteria**
- The schools should have details( email, site, telephone number, email ...etc)
- The comments to the school should be public

# View Schoool Details

### Star rating / Ask a question / Give review
- As a user, I need a right to give a star rating to the school so I can help other parents
- As a user, I need to post a question then I can get an answer from the school manager or other users
-  As a user, I need to give my feedback to the school so I can help other users
- As a school manager I can reply to users question or comments so parents can get the right answer 

**Acceptance Criteria**
- The comments to the school should be public
-  User can reply to each other

# General

### Read Belgium secondary education information / News

- As a user, I need information on how is the secondary school in Belgium so that it helps me to decide which school is comfortable for my child
- As a school manager I can post general news about the new information so parents can get information easily

**Acceptance Criteria**
- There is enough information on a secondary school in Belgium
- There is news or any updates on a secondary school in Belgium

**Comment by KrisBaes007** [comment]
Feruz, this looks like a collection of user stories, which would benefit from being split up into individual ones. That way you have an easier time detailing the description + acceptance criteria, but it also allows more people to work on them simultaneously. I will share a mini tutorial about story splitting with some basic patterns on Slack.

**Comment by Feruzteame** [comment]
understood! thank you @KrisBaes007
