### ISSUE TITLE
Check consistency between the site map and the different screens in the Wireframes

### ISSUE THREAD

**Issue by mamoo** [Hack-Your-Future-Group-A-Dream-Team/iSchool#9]
Every page in the sitemap should* have a corresponding wireframe developed

(*) very similar pages can be associated to only one wireframe, provided that this is made clear to everyone (especially the person who's going to design the website)

**Comment by razvanbrb** [comment]
Please check the flow of the pages @julia-sod  and @fmkarakus . The Flow page you can check it on this link https://app.flowmapp.com/projects/183250/userflow/125238/.  LEt me know if I have to edit or change something. Thanks.

**Comment by razvanbrb** [comment]
Done
